# Generated by Django 6.1.1 on 2026-09-08 11:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'ordering': ['nom', 'prenom']},
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['nom', 'prenom']},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['date_examen']},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={'ordering': ['etudiant']},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['date_debut', 'nom']},
        ),
        migrations.AddField(
            model_name='inscription',
            name='note_examen',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Note d'examen sur 10", max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='inscription',
            name='note_interro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Note d'interrogation sur 5", max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='inscription',
            name='note_tp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note de travaux pratiques sur 5', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='app.examen'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne sur 20 (calculée)', max_digits=4, null=True),
        ),
    ]
