# Generated by Django 6.1.1 on 2026-09-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cours_options_alter_enseignant_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['nom'], name='app_cours_nom_b7dd73_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['promotion', 'nom'], name='app_cours_promoti_28b714_idx'),
        ),
        migrations.AddIndex(
            model_name='enseignant',
            index=models.Index(fields=['nom', 'prenom'], name='app_enseign_nom_ba8208_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['nom', 'prenom'], name='app_etudian_nom_c891c7_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['promotion', 'nom', 'prenom'], name='app_etudian_promoti_2a0c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['date_examen'], name='app_examen_date_ex_5a87e4_idx'),
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['session', 'date_examen'], name='app_examen_session_9d4698_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['examen', 'etudiant'], name='app_inscrip_examen__8e5528_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['nom'], name='app_promoti_nom_4682f8_idx'),
        ),
    ]
