# Generated by Django 6.1.1 on 2026-09-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cours_app_cours_nom_b7dd73_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examen',
            constraint=models.UniqueConstraint(fields=('cours', 'session'), name='unique_examen_cours_session', violation_error_message='Un examen existe déjà pour ce cours dans cette session.'),
        ),
    ]
