# Generated by Django 6.1.1 on 2026-09-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_examen_unique_examen_cours_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='est_note',
            field=models.BooleanField(default=False, help_text="Indique si les copies de cet examen ont été corrigées (l'examen est alors signalé comme noté).", verbose_name='Noté'),
        ),
    ]
