# Generated by Django 6.1.1 on 2026-09-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_examen_est_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='est_active',
            field=models.BooleanField(default=False, help_text="Désigne la session d'examens actuellement en cours. Une seule session peut être active à la fois.", verbose_name='Session en cours'),
        ),
    ]
