# Generated by Django 6.1.1 on 2026-09-15 13:48

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_session_est_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['noms']},
        ),
        migrations.RemoveIndex(
            model_name='etudiant',
            name='app_etudian_nom_c891c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='etudiant',
            name='app_etudian_promoti_2a0c0e_idx',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='noms',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='numero_etudiant',
            field=models.CharField(blank=True, default=app.models.generate_numero_etudiant, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['noms'], name='app_etudian_noms_88abef_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['promotion', 'noms'], name='app_etudian_promoti_bfd69a_idx'),
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='prenom',
        ),
    ]
