# Generated by Django 6.1.1 on 2026-09-15 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_etudiant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'ordering': ['etudiant__noms']},
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='examen',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='app.cours'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='app.session'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='app.etudiant'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('etudiant', 'examen'), name='unique_inscription_etudiant_examen'),
        ),
    ]
