# Generated by Django 6.1.1 on 2026-09-15 14:54

from django.db import migrations, models


def _fusionner_nom_prenom(apps, schema_editor):
    Enseignant = apps.get_model('app', 'Enseignant')
    for e in Enseignant.objects.all().only('id', 'nom', 'prenom'):
        noms = f"{e.nom or ''} {e.prenom or ''}".strip()
        noms = ' '.join(noms.split())
        Enseignant.objects.filter(pk=e.pk).update(noms=noms)


def _scinder_noms(apps, schema_editor):
    Enseignant = apps.get_model('app', 'Enseignant')
    for e in Enseignant.objects.all().only('id', 'noms'):
        parts = (e.noms or '').split(' ', 1)
        Enseignant.objects.filter(pk=e.pk).update(
            nom=parts[0] if parts else '',
            prenom=parts[1] if len(parts) > 1 else '')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_inscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='noms',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RunPython(_fusionner_nom_prenom, _scinder_noms),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'ordering': ['noms']},
        ),
        migrations.RemoveIndex(
            model_name='enseignant',
            name='app_enseign_nom_ba8208_idx',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='prenom',
        ),
        migrations.AddIndex(
            model_name='enseignant',
            index=models.Index(fields=['noms'], name='app_enseign_noms_092c89_idx'),
        ),
    ]
