# Generated by Django 6.1.1 on 2026-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_enseignant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='cours',
            name='app_cours_nom_b7dd73_idx',
        ),
        migrations.RemoveIndex(
            model_name='cours',
            name='app_cours_promoti_28b714_idx',
        ),
        migrations.RemoveIndex(
            model_name='promotion',
            name='app_promoti_nom_4682f8_idx',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('promotion', 'nom'), name='unique_cours_promotion_nom', violation_error_message='Ce cours existe déjà pour cette promotion.'),
        ),
    ]
