# Generated by Django 6.1.1 on 2026-09-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_inscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='numero_etudiant',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
