# Generated by Django 6.1.1 on 2026-09-19 14:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_etudiant_numero_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20)),
                ('etablissement', models.CharField(blank=True, default='', max_length=100, verbose_name='Établissement')),
                ('intitule', models.CharField(blank=True, default='', max_length=200)),
                ('total_credits', models.PositiveSmallIntegerField(default=0, help_text='Somme des crédits des UE (dénominateur de la moyenne).')),
                ('fichier_source', models.CharField(blank=True, default='', help_text="Nom du fichier Excel d'origine (traçabilité).", max_length=255)),
                ('importe_le', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles', to='app.promotion')),
                ('session', models.ForeignKey(blank=True, help_text="Session d'examens où la grille est consultée.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grilles', to='app.session')),
            ],
            options={
                'ordering': ['-importe_le'],
            },
        ),
        migrations.CreateModel(
            name='GrilleEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.PositiveSmallIntegerField(help_text="N° d'ordre de l'étudiant dans la grille.")),
                ('credits_s1', models.PositiveSmallIntegerField(default=0)),
                ('credits_s2', models.PositiveSmallIntegerField(default=0)),
                ('credits_total', models.PositiveSmallIntegerField(default=0)),
                ('nb_ue_reprendre', models.PositiveSmallIntegerField(default=0, verbose_name='UE à reprendre')),
                ('total_pondere', models.PositiveIntegerField(default=0)),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne /20 délibérée (null si non calculable).', max_digits=4, null=True)),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, help_text='Réussite en pourcentage (0-100).', max_digits=5, null=True)),
                ('decision', models.CharField(blank=True, choices=[('V', 'Validé'), ('VC', 'Validé avec complément'), ('NV', 'Non validé')], default='', max_length=2)),
                ('mention', models.CharField(blank=True, choices=[('Passable', 'Passable'), ('Assez Bien', 'Assez Bien'), ('Bien', 'Bien'), ('Très Bien', 'Très Bien'), ('Excellent', 'Excellent')], default='', max_length=20)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grille_lignes', to='app.etudiant')),
                ('grille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='app.grille')),
            ],
            options={
                'ordering': ['rang'],
            },
        ),
        migrations.CreateModel(
            name='GrilleUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('credits', models.PositiveSmallIntegerField(default=1)),
                ('semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')])),
                ('groupe', models.CharField(blank=True, default='', help_text="Code du groupe d'UE du fichier (IBA, LAN, MIF…).", max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Position de la colonne dans le fichier.')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grille_ues', to='app.cours')),
                ('grille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='app.grille')),
            ],
            options={
                'ordering': ['semestre', 'ordre', 'intitule'],
            },
        ),
        migrations.CreateModel(
            name='GrilleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, help_text='Note /20 (null = case vide dans la grille).', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.grilleetudiant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.grilleue')),
            ],
        ),
        migrations.AddIndex(
            model_name='grille',
            index=models.Index(fields=['promotion', 'annee_academique'], name='app_grille_promoti_f474e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='grille',
            constraint=models.UniqueConstraint(fields=('promotion', 'session', 'annee_academique'), name='unique_grille_promotion_session_annee', violation_error_message='Une grille existe déjà pour cette promotion dans cette session et cette année académique.'),
        ),
        migrations.AddConstraint(
            model_name='grilleetudiant',
            constraint=models.UniqueConstraint(fields=('grille', 'etudiant'), name='unique_grilleetudiant_grille_etudiant', violation_error_message='Cet étudiant figure déjà dans la grille.'),
        ),
        migrations.AddConstraint(
            model_name='grilleetudiant',
            constraint=models.UniqueConstraint(fields=('grille', 'rang'), name='unique_grilleetudiant_grille_rang', violation_error_message="Ce numéro d'ordre est déjà utilisé dans la grille."),
        ),
        migrations.AddConstraint(
            model_name='grilleue',
            constraint=models.UniqueConstraint(fields=('grille', 'intitule'), name='unique_grilleue_grille_intitule', violation_error_message='Cette UE figure déjà deux fois dans la grille.'),
        ),
        migrations.AddIndex(
            model_name='grillenote',
            index=models.Index(fields=['ue', 'ligne'], name='app_grillen_ue_id_d14f9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='grillenote',
            constraint=models.UniqueConstraint(fields=('ligne', 'ue'), name='unique_grillenote_ligne_ue', violation_error_message='Cette note existe déjà pour cet étudiant et cette UE.'),
        ),
    ]
