# Generated by Django 6.1.1 on 2026-09-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_grille_grilleetudiant_grilleue_grillenote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grilleetudiant',
            name='total_pondere',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total pondéré délibéré (notes × crédits). Décimal car des grilles comportent des notes à 1 décimale, ex. 16,2 → total 731,20.', max_digits=8),
        ),
    ]
