# Generated by Django 6.1.1 on 2026-09-19 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_grilleetudiant_total_pondere'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_promotions', to='app.etudiant')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.promotion')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
