# Generated by Django 6.1.1 on 2026-09-21 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_historiquepromotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiquepromotion',
            options={'ordering': ['-annee_academique', '-date_debut']},
        ),
        migrations.AddField(
            model_name='historiquepromotion',
            name='annee_academique',
            field=models.CharField(blank=True, default='', help_text="Année de l'étape, ex. « 2024-2025 ».", max_length=20),
        ),
        migrations.AddField(
            model_name='historiquepromotion',
            name='grille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcours', to='app.grille'),
        ),
        migrations.AddConstraint(
            model_name='historiquepromotion',
            constraint=models.UniqueConstraint(fields=('etudiant', 'promotion', 'annee_academique'), name='unique_parcours_etudiant_promotion_annee', violation_error_message='Cette étape de parcours existe déjà pour cet étudiant.'),
        ),
    ]
