# Generated by Django 6.1.1 on 2026-09-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_historiquepromotion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grilleetudiant',
            name='noms',
            field=models.CharField(blank=True, default='', help_text="Nom tel qu'écrit dans la grille (recopié tel quel, même quand la ligne est rattachée à une fiche).", max_length=150),
        ),
        migrations.AlterField(
            model_name='grilleetudiant',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grille_lignes', to='app.etudiant'),
        ),
    ]
